# Generated by Django 5.1.5 on 2025-01-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_qr_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcodelog",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="qrcodelog",
            name="created_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="qrcodelog",
            name="file_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="qrcodelog",
            name="qr_code_path",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
